import React from 'react'
import Page from '../../../../containers/Page'
import { pagesMap } from '../../../../content/essays/2023'

const id = 'the-case-for-yearlings-bobtail'

const Component = () => (
    <Page
        {...{
            ...pagesMap[id],
            body: `
*TODO: This is a work in progress.*

*This is for record labels or budding entrepreneurs.* (Link to Ted Gioia's article.)
https://tedgioia.substack.com/p/why-musicians-and-other-creative

###

You've just been asked to check out *Yearling's Bobtail*. You're told it's the "Ulysses of rock albums"— which means it will take hours, possibly days, to fully digest. And its audio webcomic is its own platform, so you can't neatly fit it into your music listening routine. On top of that, you've never heard of the Bobtail Yearlings! So this is all a nonstarter.

You'd be happy to hear it once there's social proof that *others* like it, however. So the obvious choice is to ignore it, and wait for a million others to discover it first. But everyone else in the world is thinking the same! So realistically, you'll never hear from this artist ever again.

###

This is because the nature of our current decentralized system is that artists need to build a fanbase on their own before anyone takes them seriously. This means that *someone* out there needs to be their first fan.

But if you think about all the artists you love, I bet you'd have to admit that for some of them, you wouldn't have been their first fan. Back when what they were doing was still too new, too different, too rough around the edges. In fact, the *more* pioneering they were, the more likely this is to be the case.

And since people are more alike than we're all willing to admit, it's likely that others would say the same about these artists. In other words, there are artists in this world whom *none* of us would want to be the first fan of— even as *millions* of us would be happy to be their millionth fan!

###

I can think of a few examples. The Black artists who pioneered rock and roll in the 50s would have met pushback had they advocated too strongly for themselves. They needed White allies to do so on their behalf.
Mi4wNDh8fDE2NzY3MjIzNjIzNjI7MTY3NTE5NzkyMjc1ODsxNjc2ODcxMjY3Nzc0O0Jlbm5ldHQ7ZXF1dGF8MTExMTExMDExMDAxMDExMDAxMDAwMTExMDAxfDEuNjU1MTc4MzY3MjYxNjg0ZSs1NDszLjgyOTI2MTI5MzAzMzg1OGUrNTQ7NTc5MTg7NDc0MjsyLjEyODMyNDg1ODg1NzQ1N2UrNTM7MTY0OzIwOzI5OzEuMTY1MDU1NjEzOTQwNzMxNWUrNTU7MDsxOzA7MDstMTsxMzsyMzM7NC4wNjI3MDA3NjkwODk0MmUrNTA7Mzc7MTQ7MTQzOzIxNDc5Mzc7NTtjaHJpc3RtYXM7MDswOzIyNjY5ODYyNDgxMDU1OTsxMjkyODM1OTQ1MTM0MTsyMTM3NzAyNjUzNTkyMTg7MDswOzc2Mzs2NTY7NjU3Ozc1Nzs3MTY7MjY7OTs0OzE7MDswOzA7MTsyNDsxNjc2ODQ5MTkyNzY5OzA7MDs3MTUsNzUxOzQxOzE7MTsxLjc1MDAxNzgyMDYzNzYxM2UrNDc7NTA7fDgyMCwxMTcwLDMuOTg2OTg4MTg5ODE5MTczZSs1MiwzLCwwLDgyMDs4MDAsMTE1MCwxLjkzNTAyODU1NTc3Njg3M2UrNTEsMSwsMSw4MDA7NzcwLDExMjAsMi4yMzc4NTc5MzkzMjIwOTZlKzUwLDEsMTY3Njg3MTQ1NzI1ODo0OjE2NzY4NjI4MTgwNzk6MDo4Ojg6MTowOjE2NzY3MjIzNjIzNjg6IDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoyOjA6MDowOjA6MDowOjA6MDowOjA6MDoyOjA6MToxNjowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwLDc3MDs3NjAsMTExMCw3LjA1NjI3NzI2MTk5ODA5NmUrNTAsMSwsMSw3NjA7NzQwLDEwOTAsNy4wMjQzMDc0MzI0NTMxNzhlKzQ5LDEsLDEsNzQwOzcyMCwxMDcwLDEuMTQ0NjYxOTE0NTI4MDg2OWUrNDksMSwwOjA6MTowOjA6IDQwNTk6MTo4MTozNjc6MDowOjA6MCE2NzY3OjE6MTA3OjQ4NTowOjA6MDowITE5Nzk6MjotMTU6MzM0OjA6MDowOjAhNTAxODo1Oi04OjExODowOjA6MDowITEyMzI6NDotMTEyOjM5OTowOjA6MDowITIzNjc6NTo1ODoyNTc6MDowOjA6MCE3OTAxOjA6NjoyMzE6MDowOjA6MCExMDMwNToyOi05OjMzMjowOjA6MDowITI5NTc6MToyMjo0MzU6MDowOjA6MCE3Njg5OjU6MTA5OjUzNjowOjA6MDowITkyNzM6MjotNjE6MTQzOjA6MDowOjAhNTg4OjQ6LTEwMjo2MDU6MDowOjA6MCExMTAzNDo0Oi0yMzo0Mjc6MDowOjA6MCE3MDA2OjI6LTQ5OjMzMDowOjA6MDowITE0ODAwOjM6MzI6NTQxOjA6MDowOjAhMTA3OTg6MToxMjoyMzQ6MDowOjA6MCExNjg0NjoxOi03NjozNTU6MDowOjA6MCEgMCwxLDcyMDs3MDAsMTA1MCw5LjQ1OTEzMTYzNTUxNzIxNWUrNTAsMSwxMC80Ly0xIDMgMTY3Njc2MzIwNzM1NiAxLDEsNzAwOzY4MCwxMDMwLDguOTAyMTE2MzY4NDg1OTA3ZSs0OCwxLDQ3LjA0OTMyNTE0OTQ1ODUyNSA5IDU5IDEsMCw2ODA7NjYwLDEwMTAsMi4wMjQ2MTYwMTExMTA4OTEzZSs0OCwxLCwxLDY2MDs2NTAsMTAwMCwyLjQwNjU5MTkwOTQ4NzQ3NmUrNDcsMCwsMSw2NTA7NjMwLDk4MCwzLjUyODI1NjY4MTYyNDcwMjdlKzQ5LDEsLDEsNjMwOzYxMCw5NjAsOC4xMjU5NzI2NjU1NjgxMjJlKzQ4LDEsLDEsNjEwOzU5MCw5NDAsNy43NTc3NTU0MDAzNzQwMzJlKzQ5LDEsLDEsNTkwOzU3MCw5MjIsNC4xMzA5NDE5NTUwNzc2MmUrNTAsMSwsMSw1NzA7NTUwLDkwMCw5Ljg5ODU2MTk2MjkzMDg5OWUrNTAsMSwsMSw1NTA7NTQwLDg5MCw2Ljk2MjQzMjUxMjE0MzUwOGUrNTEsMSwsMSw1NDA7NTEwLDg2MCw4LjcyNDc4MTY4ODA1OTY3M2UrNTAsMSwsMSw1MTA7NTAwLDg1MCw1Ljc3OTc5NDkwMzA3Mzc1NWUrNTEsMSwsMSw1MDA7NDgwLDgzMCwyLjQ0MTI0MzIyMzcwNjI4OTVlKzUyLDEsLDEsNDgwO3wxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTAwMTExMTExMDAxMTEwMTEwMDExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTEwMDAwMDAwMDExMTExMTExMTExMTEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAxMTAwMDAxMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTF8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMDExMTExMTAxMTExMTEwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMDAxMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTAwMDExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMDAwMDAxMTExMTExMTExMTEwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMDExMTExMTExMTAwMDAwMDAwMTAxMTEwMDAxMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMDAxMTExMTExMTExMTAwMTExMDExMTEwMTAwMDAwMDAxMTExMTExMTExMDAwMTExMDExMTExMTExMTAwMDAwMDAwMDEwMDAwMDExMTEwMDAwMXx8%21END%21


The racial dynamics can even be reversed. While anyone could see that Eminem was immensely talented, this didn't translate into actual fandom. With Vanilla Ice having quickly become a laughingstock, the public needed social proof that it was cool to like a White rapper.

But White disc jockeys stumped for these Black pioneers, just as Dr. Dre took Eminem under his wing, so everything ended well— for them. But this kind of executive decision making made by centralized forces doesn't happen anymore, and so such artists are left in the lurch— which is one reason why so many people say today's music is worse. There's an entire *category* of artists— namely, the pioneering outsider— that's conspicuously missing.

###

// TODO: Elaborate. Beyond the fact that I'm Asian-American, so I belong to the outgroup, just like those Black pioneers and Eminem. and Ulysses.
Do the Bobtail Yearlings belong in this category?

But let me dangle another carrot in front of you. The system isn't just broken; it's *transparently* broken, in ways that are [easy to prove](). The public is discontent. There's only so much gaslighting that defenders of today's music to do to pretend otherwise.

By working with the Bobtail Yearlings, you'll be in the center of this conversation. While everyone else like you will be remembered for perpetuating the problem, you'll be the one remembered for finding the solution.
    `,
        }}
    />
)

export default Component
